config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server.new, at: "/resque"
  
  namespace :api do

    namespace :v1 do
      get 'home', to: 'posts#home'
      post 'posts/create', to: 'posts#create'
      post 'users/sign_in', to: 'users#sign_in'
    end

    namespace :v2 do
       get 'home', to: 'posts#home'

    end

  end



  get 'users/profile/:id', to: 'users#profile'
  get 'users/search', to: 'users#search'
 

  post 'users/upload_avatar/:id', to: 'users#upload_avatar', as: :user_avatar_upload
  

  post 'likes/toggle/:post_id', to: 'likes#toggle', as: :toggle_like

  post 'comments/create', as: :comments
  delete 'comments/:id', to: 'comments#destroy', as: :destroy_comment

	# Post routes
  root 'posts#home'
  get 'posts/home', to: 'posts#home'
  post 'posts/create', as: :posts
  delete 'posts/:id', to: 'posts#destroy', as: :destroy_post

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy


	# returns true if a user can like this post
	def user_can_like(user_id)
		if self.likes.where(user_id: user_id).length > 0
			return false
		end

		return true

	end


	def like_status_string(user_id)
		if self.user_can_like(user_id)
			return '<i class="fa fa-thumbs-up"></i>'.html_safe
		else
			return '<i class="fa fa-thumbs-down"></i>'.html_safe

		end

	end

end

app/controllers/api/v1/posts_controller.rb
module Api
	module V1
		class PostsController < ApplicationController
			before_action :set_api_current_user, only: [:create]

			def home
				@posts = Post.all
				return render json: @posts

			end

			def create
				
				new_post = Post.create(post_params)

				new_post.user = @api_current_user
				new_post.save
				return render json: new_post
			end

			private

			def post_params
				params.require(:post).permit(:content, )
			end

		end
	end
end

app/controllers/api/v2/posts_controller.rb
module Api
	module V2
		class PostsController < ApplicationController
			def home
				@posts = Post.all
				return render json: @posts, each_serializer: PostDetailSerializer

			end

		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_post, only: [:destroy]
  before_action :authorize_user, only: [:destroy]

  def home
    # for new posts
  	@post = Post.new

    # for list of posts
  	@posts = Post.all

    # for new comment
    @comment = Comment.new

    @all_users = User.all.order("id").pluck(:email)
    @user_ids = User.all.order("id").pluck(:id)

    # this is specific for returning the defined formats, if we remove this block and just render json directly, it will send only json for all formats
    respond_to do |format|
      format.html
      format.json {
          if params[:details] == "true"
              return render json: @posts, each_serializer: PostDetailSerializer
          else
              return render json: @posts
          end

          
       }

    end

  end

  def create

  	@post = Post.create(content: params[:post][:content], user_id: current_user.id)
  	@comment =Comment.new
    # commented for using js request as well
    # redirect_to action: "home"

  end

  def destroy
    @post_id = @post.id
	@post.destroy

  	# redirect_to action: "home"
  end


  private

  def set_post
  	@post = Post.find(params[:id])
  end

  def authorize_user
  	if (@post.user_id != current_user.id)
  		redirect_to action: "home"
  	end

  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>" class="wow animated fadeInUp">
	<div>

		<p><%= post.content %></p>
		<p><%= post.user.email %></p>
		<% if user_signed_in? && post.user_id ==  current_user.id %>
		<p><%= link_to "Delete", destroy_post_path(post.id), method: :delete, remote: true %></p>
		<% end %>

		<% if user_signed_in? %>
		<p>
			<sub id="post-<%= post.id %>-likes" class="post-like-status">
				<%= render 'post_like_link', post: post %>
			</sub>
		</p>
		<% else %>
		<sub>
				<%= post.likes.length %> Likes
		
			</sub>

		<% end %>

		<div>
			<%= render 'comments/post_comment', post: post %>
		</div>
		
	</div>
</li>

app/views/posts/_post_like_link.html.erb
<span>

	<%= post.likes.length %>

	<%= link_to post.like_status_string(current_user.id), toggle_like_path(post.id), method: :post, remote: true %>

</span>

app/views/posts/create.js.erb
console.log("new post created");


var newPost = $('<%= escape_javascript render "post", post: @post %>');

$('#posts-list').prepend(newPost);

new Noty({
    text: 'Someone just posted!',
    theme: 'relax',
    type: 'warning',
    layout: 'topRight',
    timeout: 1000,
}).show();

app/views/posts/destroy.js.erb
console.log('destroy post called');

$('#post-<%= @post_id %>').remove();

new Noty({
    text: 'Post Deleted',
    theme: 'relax',
    type: 'warning',
    layout: 'topRight'
}).show();

app/views/posts/home.html.erb
<main id="posts-home">

	<div class="hide-small-screen">Group Links</div>

	<div class="deewar-posts">
		<div class="new-post-form">
			<% if user_signed_in? %>
			<%= form_for @post, remote: true do |f| %>
				<%= f.label :content %>
				<%= f.text_area :content %>

				<%= f.submit %>
			<% end %>
			<% end %>
		</div>

		<div >
			<ul id="posts-list" class="posts-list">
				<% @posts.reverse.each do |p| %>
				<!--  -->
					<%= render 'post', post: p %>
				<% end %>
			</ul>


		</div>
		

	</div>


	<div class="hide-small-screen">
		<h4>Friends</h4>
		<input id="user-search" type="text" placeholder="Search...">
	</div>

	<script type="text/javascript">
	{
	
		 $( "#user-search" ).autocomplete({
		      source: '/users/search',
		      minLength: 2,
		      select: function( event, ui ) {
		      	 
		      	// console.log(user_ids[]);
		      	console.log(ui.item);
		      	window.location = '/users/profile/' + ui.item.id;
		      }
		    });

	}
	


	</script>

</main>